### ISSUE TITLE
Device attributes

### ISSUE THREAD

**Issue by trinayan** [RadeonOpenCompute/ROCR-Runtime#1]
So I upgraded the ROCR runtime recently. I remember in the previous version when running the vector copy it used to show the agent name is Spectre. But now it shows the agent name is Kaveri. I know that the Kaveri APU has the Spectre GPU. But was little bit skeptical if everything is working as it should be. I can execute applications correctly though. But just confused about this. Could anyone verify if it should return Spectre or Kaveri?.

**Comment by jedwards-AMD** [comment]
If the agent being returned is the GPU agent, it should be named Spectre. This is a known issue and should be fixed in an upcoming release.
