### ISSUE TITLE
For the HSA user-defined queue, when will the read index of the ring buffer be updated?

### ISSUE THREAD

**Issue by lscat11** [RadeonOpenCompute/ROCR-Runtime#105]
For AMD GPU, is the read index updated after the compute kernel dispatched by a AQL packet finished?

**Comment by t-tye** [comment]
The AQL protocol is defined in:

- [2.8 Requirement: User mode queuing](http://www.hsafoundation.com/html_spec111/HSA_Library.htm#SysArch/Topics/02_Details/req_user_mode_queuing.htm%3FTocPath%3DHSA%2520Platform%2520System%2520Architecture%2520Specification%2520Version%25201.1%2520%7CChapter%25202.%2520System%2520Architecture%2520Requirements%253A%2520Details%7C2.8%2520Requirement%253A%2520User%2520mode%2520queuing%7C_____0)
- [2.9 Requirement: Architected Queuing Language (AQL)](http://www.hsafoundation.com/html_spec111/HSA_Library.htm#SysArch/Topics/02_Details/req_architected_queuing_language_AQL.htm%3FTocPath%3DHSA%2520Platform%2520System%2520Architecture%2520Specification%2520Version%25201.1%2520%7CChapter%25202.%2520System%2520Architecture%2520Requirements%253A%2520Details%7C2.9%2520Requirement%253A%2520Architected%2520Queuing%2520Language%2520(AQL)%7C_____0)

The read pointer may advance any time after the dispatch packet has been initiated. For the current AMD implementation it will advanced in reasonable finite time after the dispatch has completed, but an application should only rely on the published specification and not one specific implementation details which could change in future releases.

**Comment by fxkamd** [comment]
In my experience, the readpointer writeback to memory can be delayed on the order of milliseconds. We use this in some of our low-level tests for simplicity. In tests where performance matters, we use signals. In a real application, I'd only use the rptr to check free space in the queue, not as an indication of command completion.
