### ISSUE TITLE
Is it possible to read Global Data Share(GDS) using PM4 packets

### ISSUE THREAD

**Issue by lscat11** [RadeonOpenCompute/ROCR-Runtime#106]
Hi, I recently do some experiments with the global data share(GDS).
The question is that after I write some bytes into GDS using `ds_write` instruction, how to read them using PM4 packets without launch a "blit kernel".
I have tried PACKET3_COPY_DATA and PACKET3_DMA_DATA, but these packets will hang and never return. 
I was wondering if it is possible to read GDS using PM4 packets.

**Comment by skeelyamd** [comment]
ROCr does not currently support making GDS allocations.  ds_write from a compute kernel will be out of bounds and so discarded by HW.  As to the hang, your queues are almost certainly not hung.  If you registered a queue error callback at queue creation time you should see that the queue has detected an invalid packet and entered the error state.
