### ISSUE TITLE
Won't compile

### ISSUE THREAD

**Issue by UltraBlackLinux** [RadeonOpenCompute/ROCR-Runtime#110]
So I got this (I already tried without linking the libraries, more errors):
```
[  1%] Built target hsa_lib_link2
clang-11: error: cannot find device library for gfx1031. Provide path to different ROCm installation via --rocm-path, or pass -nogpulib to build without linking default libraries.
make[2]: *** [image/blit_src/CMakeFiles/opencl_blit_objects.dir/build.make:176: image/blit_src/ocl_blit_object_gfx1031] Fehler 1
make[1]: *** [CMakeFiles/Makefile2:231: image/blit_src/CMakeFiles/opencl_blit_objects.dir/all] Fehler 2
make: *** [Makefile:171: all] Fehler 2
```
I also don't know the library's path, so that's a problem..
I hope there is a solution for that, this non-updated build is camping my aur updates for quite some while now, and I want to get rid of it...
Thanks!

**Comment by skeelyamd** [comment]
Have you updated your ROCm clang and device libs packages?  ROCr depends on those for image support.  If you don't need image support you can avoid these dependencies by switching that option off.

**Comment by UltraBlackLinux** [comment]
@skeelyamd 
Device libs are up to date, I even tried to install the clang thing (weird that I even got the rocm stuff to install in the first place) but got more errors :|
```
/home/maus/Downloads/clang-amd-common/utils/TableGen/ClangASTNodesEmitter.cpp:175:53: Fehler: »llvm::StringRef« kann nicht nach »std::string« {aka »std::__cxx11::basic_string<char>«} umgewandelt werden
  175 |   OS << "#undef ABSTRACT_" << macroName(Root.getName()) << "\n";
      |                                         ~~~~~~~~~~~~^~
      |                                                     |
      |                                                     llvm::StringRef
/home/maus/Downloads/clang-amd-common/utils/TableGen/ClangASTNodesEmitter.cpp:37:44: Anmerkung:   Argument 1 von »static std::string {anonymous}::ClangASTNodesEmitter::macroName(std::string)« wird initialisiert
   37 |   static std::string macroName(std::string S) {
      |                                ~~~~~~~~~~~~^
make[2]: *** [utils/TableGen/CMakeFiles/obj.clang-tblgen.dir/build.make:82: utils/TableGen/CMakeFiles/obj.clang-tblgen.dir/ClangASTNodesEmitter.cpp.o] Fehler 1
make[1]: *** [CMakeFiles/Makefile2:2822: utils/TableGen/CMakeFiles/obj.clang-tblgen.dir/all] Fehler 2
make: *** [Makefile:149: all] Fehler 2
```
and many more of that kind..
Hope this helps, thanks for your effort!

**Comment by onodera-punpun** [comment]
Running into the exact same error, I have `rocm-device-libs` installed however

**Comment by skeelyamd** [comment]
This may be due to LLVM now requiring a newer stdlib ABI.  Which compiler are you using?

**Comment by skeelyamd** [comment]
@searlmc1, can you comment on the above compilation errors?

**Comment by UltraBlackLinux** [comment]
@skeelyamd https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=llvm-amdgpu

**Comment by skeelyamd** [comment]
As stated above please use a newer compiler / stdlib.  LLVM requires a C++17 compliant stdlib and older versions of gcc do not support the new string constructor syntax.  Feel free to reopen if you have upgraded your compiler and rebuilt lightning without resolving the issue.
