### ISSUE TITLE
Any 4.0.x version?

### ISSUE THREAD

**Issue by gmarkomanolis** [RadeonOpenCompute/ROCR-Runtime#111]
Hi,

I assume this is typical as it seems the 3.10.x works but as we install everything from scratch, could you make available a 4.0.x branch to comply with the rest ROCm repos?

thank you,
George

**Comment by powderluv** [comment]
any updates on this for 4.0.x ?

**Comment by yalue** [comment]
There may not be a 4.0.x branch, but there is at least a rocm-4.0.0 tag, if that helps.  It points to the commit where 3.10 was merged into master.  So, for the time being, 4.0.0 is exactly equivalent to the tip of 3.10.

**Comment by skeelyamd** [comment]
4.0.1 was a point release to fix specific bugs only.  ROCr had no updates relevant to these bugs so remains at 4.0.0 (which as pointed out above is also identical to 3.10).

**Comment by gmarkomanolis** [comment]
One generic comment, it would be great for all the related to ROCm parts to have same approach about versioning and always name one even if it is the same with older one. This way some scripts can find always a repository branch or tag if we ask for the 4.0.0 for example. In some ROCm repos, there is an updated branch version for example, in some other only tags. When I select the tag rocm-4.0.0 shoes last commit of 3.10.0 and no other explanation that nothing was updated, so this is not a mistake. Just maybe try to commit even a text change or something at least to feel like pointing in the correct version. Thanks for your work!

**Comment by JonChesterfield** [comment]
I believe 4.1 is tagged, see https://github.com/RadeonOpenCompute/ROCR-Runtime/tree/rocm-4.1.x
