### ISSUE TITLE
Using textures causes "Depth set on single layer image geometry."

### ISSUE THREAD

**Issue by ex-rzr** [RadeonOpenCompute/ROCR-Runtime#113]
The runtime prints this message to stderr:
https://github.com/RadeonOpenCompute/ROCR-Runtime/blob/master/src/image/hsa_ext_image.cpp#L81

According to HSA specs (http://www.hsafoundation.com/html/Content/Runtime/Topics/03_Extensions/hsa_ext_image_descriptor_t.htm):

> height
Height of the image, in components. Only **defined** if the geometry is 2D or higher.
> depth
Depth of the image, in components. Only **defined** if geometry is HSA_EXT_IMAGE_GEOMETRY_3D. **A depth of 0 is same as a depth of 1.**
> array_size
Number of images in the image array. Only **defined** if geometry is HSA_EXT_IMAGE_GEOMETRY_1DA, HSA_EXT_IMAGE_GEOMETRY_2DA, or HSA_EXT_IMAGE_GEOMETRY_2DADEPTH.

It seems that ROCR-Runtime and ROCclr both have issues:

1. ROCR-Runtime checks for depth != 0 incorrectly because "A depth of 0 is same as a depth of 1."

2. ROCclr sets height, depth, array_size to 1 (https://github.com/ROCm-Developer-Tools/ROCclr/blob/main/device/rocm/rocmemory.cpp#L959)
However, it's unclear what "defined" means here: 1) incorrect values should be ignored 2) fields can have any values.

**Comment by skeelyamd** [comment]
This spec text was changed in HSA v1.1.  It now reads as must be 0.

http://www.hsafoundation.com/html_spec111/HSA_Library.htm#Runtime/Topics/03_Extensions/hsa_ext_image_descriptor_t.htm%3FTocPath%3DHSA%2520Runtime%2520Programmer%25E2%2580%2599s%2520Reference%2520Manual%2520Version%25201.1.1%2520%7CChapter%25203.%2520HSA%2520Extensions%2520Programming%2520Guide%7C3.3%2520Images%2520and%2520samplers%7C3.3.1%2520Images%2520and%2520samplers%2520API%7C_____10

**Comment by ex-rzr** [comment]
Ok, I'm closing this issue because this is a bug in ROCclr.
