### ISSUE TITLE
Intermittent memory access failure on gfx1030

### ISSUE THREAD

**Issue by powderluv** [RadeonOpenCompute/ROCR-Runtime#114]
I am running the same hello_world from the LLVM documentation from the code here using COV3 + gfx1030 and latest AOMP and rocm-4.0.x branches of others:

https://github.com/Powderluv/LLVM-AMDGPU-Assembler-Extra

However it seems to intermittently fail

```
foo@5950x:/github/LLVM-AMDGPU-Assembler-Extra/b/examples/asm-kernel$ ./asm-kernel
Using agent: gfx1030

Success
foo@5950x:/github/LLVM-AMDGPU-Assembler-Extra/b/examples/asm-kernel$ ./asm-kernel
Queue at 0x7f3899753000 inactivated due to async error:
        HSA_STATUS_ERROR_INVALID_ALLOCATION: The requested allocation is not valid.
^C
130 foo@5950x:/github/LLVM-AMDGPU-Assembler-Extra/b/examples/asm-kernel$ ./asm-kernel
Queue at 0x7f9dc3f5f000 inactivated due to async error:
        HSA_STATUS_ERROR_INVALID_ALLOCATION: The requested allocation is not valid.
^[[A^C
130 foo@5950x:/github/LLVM-AMDGPU-Assembler-Extra/b/examples/asm-kernel$ ./asm-kernel
Queue at 0x7fa0543a9000 inactivated due to async error:
        HSA_STATUS_ERROR_INVALID_ALLOCATION: The requested allocation is not valid.
^C
130 foo@5950x:/github/LLVM-AMDGPU-Assembler-Extra/b/examples/asm-kernel$ ./asm-kernel
Using agent: gfx1030

Success
```

**Comment by skeelyamd** [comment]
HSA_STATUS_ERROR_INVALID_ALLOCATION indicates an out of bounds group memory request from a kernel dispatch AQL packet.

In the example it appears that Dispatch::group_dynamic_size is uninitialized.  If this is too large then you may see this error.

**Comment by skeelyamd** [comment]
@nhaustov, can you check the LLVM example source?

**Comment by powderluv** [comment]
That is exactly the problem. I fixed the sample and pushed up an update. Thanks for the quick resolution. 

Closing the issue.
