### ISSUE TITLE
max dimension size of HSA_EXT_IMAGE_GEOMETRY_1DB

### ISSUE THREAD

**Issue by barathum000** [RadeonOpenCompute/ROCR-Runtime#115]
Hi,

We have a simple ocl test which will create a 1D image buffer with max dimension.
However, the value of max dimension we got via clGetDeviceInfo() is 4294967295 on rocm-4.0, and 65536 on rocm-3.3, can anyone help to explain why there's a huge gap  between 3.3 and 4.0?

**Comment by skeelyamd** [comment]
The values in 3.3 were legacy values that hadn't been updated for a very long time (pre-GCN).  Image limits were updated to conform with the currently supported device list.

Also note that 2DA and 3D image limits, as reported by ROCr, are also significantly larger.  These limits reflect the maximum addressable image coordinate space and are much larger than can be allocated on most systems.  The image coordinate space was made very large to support virtual textures (aka PRT).  That said, ROCm does not allocate PRT images so you will be unable to allocate a max size image.

**Comment by barathum000** [comment]
> 
> 
> The values in 3.3 were legacy values that hadn't been updated for a very long time (pre-GCN). Image limits were updated to conform with the currently supported device list.
> 
> Also note that 2DA and 3D image limits, as reported by ROCr, are also significantly larger. These limits reflect the maximum addressable image coordinate space and are much larger than can be allocated on most systems. The image coordinate space was made very large to support virtual textures (aka PRT). That said, ROCm does not allocate PRT images so you will be unable to allocate a max size image.

Got it, thanks very much for explanation!
