### ISSUE TITLE
Cannot build Runtime - sp3 missing and not found in build instructions

### ISSUE THREAD

**Issue by spstarr** [RadeonOpenCompute/ROCR-Runtime#12]
"The core runtime requires the sp3.a library to be able to compiler on x86_64 architechtures. The binaries for the sp3.a librariy can be found on the amd-codexl-analyzer GitHub repository:"

/home/spstarr/tmp/amd/ROCR-Runtime/src/core/runtime/amd_gpu_agent.cpp:59:27: fatal error: utils/sp3/sp3.h: No such file or directory
 #include "utils/sp3/sp3.h"
                           ^
Except the github repo in the build instructions do not contain the sp3 libraries or include headers.

https://github.com/RadeonOpenCompute/ROCR-Runtime/blob/master/src/utils/sp3/sp3.h but this no longer exists (says google history).

Can you please tell me where this is now found?

Thanks.

**Comment by jamborm** [comment]
I believe this refers to files removed in this commit:

https://github.com/GPUOpen-Tools/amd-codexl-analyzer/commit/f7f93b26f81021fe459c49d4d9f588332ee01aaf

so you can get them by checking out (for example) commit 04b7eead1d407275e071bc6f099a8506d671986f of GPUOpen-Tools/amd-codexl-analyzer.

Still, this is not only ugly, but in the long term I can only use this
if the sp3 library can be compiled from sources under an Open Source
license :-(

**Comment by gstoner** [comment]
We are moving away from SP3 to build the debug trap handler.   With the GCN ISA Assembler and Dissembler now integrated into LLVM compiler we no longer will have this dependency.  We are holding to our promise to make the ROCm stack fully open source from the metal on up.  You see clean up of this with ROCm 1.2 release.

The last  binary blob for the finalizer will drop with in ROCm 1.3, at this point all compiler will be running on our new LLVM compiler that do Native GCN ISA code generation.


Greg

On Aug 11, 2016, at 7:09 AM, Martin Jambor <notifications@github.com<mailto:notifications@github.com>> wrote:


I believe this refers to files removed in this commit:

GPUOpen-Tools/amd-codexl-analyzer@f7f93b2<https://github.com/GPUOpen-Tools/amd-codexl-analyzer/commit/f7f93b26f81021fe459c49d4d9f588332ee01aaf>

so you can get them by checking out (for example) commit 04b7eead1d407275e071bc6f099a8506d671986f of GPUOpen-Tools/amd-codexl-analyzer.

Still, this is not only ugly, but in the long term I can only use this
if the sp3 library can be compiled from sources under an Open Source
license :-(

**Comment by jedwards-AMD** [comment]
Check in of the 1.2 code is imminent, most likely by end of this week.

**Comment by jedwards-AMD** [comment]
The 1.2 updates have been checked into mainline.
