### ISSUE TITLE
HIP_VISIBLE_DEVICES  vs ROCR_VISIBLE_DEVICES 

### ISSUE THREAD

**Issue by etiennemlb** [RadeonOpenCompute/ROCR-Runtime#155]
Should we use HIP_VISIBLE_DEVICES or ROCR_VISIBLE_DEVICES ?

**Comment by dayatsin-amd** [comment]
HIP is one layer above ROCR and each one will mask GPUs at their respective level.

It is generally more efficient to mask the GPUs that you do not want to use the lowest level to minimize resource allocation. So this would be ROCR_VISIBLE_DEVICES.
