### ISSUE TITLE
CPU Node [0] has no GPU connected

### ISSUE THREAD

**Issue by Dekken** [RadeonOpenCompute/ROCR-Runtime#17]
I get a segfault running simple examples

LD_LIBRARY_PATH=/opt/rocm/lib ./vector_copy
CPU Node [0] has no GPU connected
Segmentation fault

Referencing: https://github.com/RadeonOpenCompute/hcc/issues/172

**Comment by fxkamd** [comment]
Sounds like KFD isn't detecting your GPU. Can you provide more information about your system?

- lspci -nn -d 1002:
- dmesg
- ls /sys/class/kfd/kfd/topology/nodes
- for x in /sys/class/kdf/kdf/topology/nodes/*; do echo; echo $x; cat $x/properties; done

**Comment by Dekken** [comment]
I have two XFX 390 BE

lspci -nn -d 1002:
01:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Hawaii PRO [Radeon R9 290] [1002:67b1] (rev 80)
01:00.1 Audio device [0403]: Advanced Micro Devices, Inc. [AMD/ATI] Device [1002:aac8]
03:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Hawaii PRO [Radeon R9 290] [1002:67b1] (rev 80)
03:00.1 Audio device [0403]: Advanced Micro Devices, Inc. [AMD/ATI] Device [1002:aac8]

dmesg: https://github.com/Dekken/gist/blob/master/out

ls /sys/class/kfd/kfd/topology/nodes
0


for x in /sys/class/kdf/kdf/topology/nodes/*; do echo; echo $x; cat $x/properties; done

/sys/class/kdf/kdf/topology/nodes/*
cat: /sys/class/kdf/kdf/topology/nodes/*/properties: No such file or directory

**Comment by fxkamd** [comment]
This is the problem:
[   60.552156] cik_smc: Failed to load firmware "radeon/hawaii_k_smc.bin"
[   60.552175] [drm:amdgpu_device_init [amdgpu]] *ERROR* sw_init of IP block <amdgpu_powerplay> failed -2
[ 60.552177] amdgpu 0000:01:00.0: amdgpu_init failed

You're missing a microcode file. The 1.3 release should have come with an updated microcode package that includes this file.

**Comment by Dekken** [comment]
Yeah I saw that in the dmesg, where should I find it/where *should* it be?

**Comment by Dekken** [comment]
It's mentioned in the 1.3 kernel

grep -R "hawaii_k_smc" /kern/rocm/1.3.x/
/kern/rocm/1.3.x/drivers/gpu/drm/amd/amdgpu/ci_dpm.c:MODULE_FIRMWARE("radeon/hawaii_k_smc.bin");
/kern/rocm/1.3.x/drivers/gpu/drm/radeon/cik.c:MODULE_FIRMWARE("radeon/hawaii_k_smc.bin");

but I don't know where it's supposed to be found

**Comment by jedwards-AMD** [comment]
This file is shipped ing the compute-firmware_1.2.515 package available in rocm 1.3.0. I checked the package, and the file exists. It should be installed in /lib/firmware/amdgpu. Local installs of the repo properly install the file.
.
What version of compute-firmware is installed on your system?

**Comment by Dekken** [comment]
I'm not sure what you mean by "firmware".

I built/installed the 1.3 ROCm Kernel, and have it booting, what else is there?

**Comment by Dekken** [comment]
I have the following under /lib/firmware/amdgpu

-rw-r--r-- 1 root root   8832 Jul 22 22:46 hawaii_ce.bin
-rw-r--r-- 1 root root  32796 Jul 22 22:46 hawaii_mc.bin
-rw-r--r-- 1 root root   8832 Jul 22 22:46 hawaii_me.bin
-rw-r--r-- 1 root root  17024 Jul 22 22:46 hawaii_mec.bin
-rw-r--r-- 1 root root   8832 Jul 22 22:46 hawaii_pfp.bin
-rw-r--r-- 1 root root   8448 Jul 22 22:46 hawaii_rlc.bin
-rw-r--r-- 1 root root   4456 Jul 22 22:46 hawaii_sdma1.bin
-rw-r--r-- 1 root root   4456 Jul 22 22:46 hawaii_sdma.bin
-rw-r--r-- 1 root root 130796 Jul 22 22:46 hawaii_smc.bin
-rw-r--r-- 1 root root 232752 Jul 22 22:46 hawaii_uvd.bin
-rw-r--r-- 1 root root 101072 Jul 22 22:46 hawaii_vce.bin


but no "hawaii_k_smc.bin" as is shown in dmesg

**Comment by jedwards-AMD** [comment]
Run this command 'dpkg --list | grep compute-firmware' and send me the version.

**Comment by Dekken** [comment]
dpkg --list | grep compute-firmware
ii  compute-firmware                                1.0.1-e295a2d                        all          Firmware support package for radeon and amdgpu driver

**Comment by fxkamd** [comment]
Firmware is microcode that runs on various micro engines on the GPU. It does things like command processing, power management, queue scheduling, etc. ROCm 1.3 added a separate version of the SMC (power management) firmware for certain versions of Hawaii cards. Your card needs the new version of the SMC microcode. So you need to install the updated firmware package that is part of the ROCm 1.3 release.

**Comment by Dekken** [comment]
I do recall having to install the microcode package previously, where can I find the updated package?

So far I have built everything from source, and wish to continue this as much as possible.

**Comment by jedwards-AMD** [comment]
The correct version of firmware for ROCm 1.3.0 is compute-firmware 1.2.515. It appears you have a previous version, shipped with ROCm 1.2.0.

**Comment by Dekken** [comment]
Please consider answering the question of "where" this is to be found.

**Comment by jedwards-AMD** [comment]
I see. You didn't install from the repo. The debian binary with the microcode can be obtained using this command:
.
 wget http://packages.amd.com/rocm/apt/debian/pool/main/c/compute-firmware/compute-firmware_1.2.515_all.deb
.

**Comment by Dekken** [comment]
Thanks, that's it indeed.

New errors

[drm:ci_set_power_profile_state [amdgpu]] *ERROR* Failed to freeze SCLK MCLK DPM!
[drm:ci_set_power_profile_state [amdgpu]] *ERROR* Failed to populate request graphics levels"

**Comment by fxkamd** [comment]
I think those messages are harmless. We're treating some return values incorrectly and taking them as errors when really everything is fine. This was fixed internally shortly after the release.

**Comment by Dekken** [comment]
Ok, then the segfault is probably important.

**Comment by fxkamd** [comment]
So is the segfault still happening?

**Comment by Dekken** [comment]
The saxpy example segfaults, I'll confirm vector_copy later today.

**Comment by Dekken** [comment]
Yes the vector_copy segfaults, without any other message.

The kernel messages appear logged to the active tty and not to out/err

**Comment by fxkamd** [comment]
I think that must be a different issued from the one originally reported. Can you get a backtrace (either using gdb or catchsegv)?

**Comment by Dekken** [comment]
https://gist.githubusercontent.com/Dekken/c296b2d225c7eff6410567eb875fc445/raw/951afd150384557553a09d72b0bae97c8018e485/gistfile1.txt

**Comment by Dekken** [comment]
I'll rebuild everything with debugging on Saturday, my build script is here if you're interseted: https://github.com/lxcy/2.0.5-x86_64-debian8.6_hcc/blob/master/setup/rocm_1.3.sh

**Comment by Dekken** [comment]
It seems there a few issues with building things using -DCMAKE_BUILD_TYPE=Debug 

Several distinct stack traces involved.

**Comment by Dekken** [comment]
The following throw stacks in Debug mode
https://github.com/RadeonOpenCompute/ROCm-Device-Libs 
https://github.com/RadeonOpenCompute/hcc

**Comment by Dekken** [comment]
Program received signal SIGSEGV, Segmentation fault.
hc::completion_future::completion_future (this=0x7fffffa21ed8, event=...) at /opt/rocm_1.3_d/hcc/include/hcc/hc.hpp:1276
1276        completion_future(std::shared_ptr<Kalmar::KalmarAsyncOp> event) : __amp_future(*(event->getFuture())), __asyncOp(event) {}

**Comment by Dekken** [comment]
Not sure what happened but vector_copy is no longer seg faulter with or without debug

LD_LIBRARY_PATH=/opt/rocm/lib  ./vector_copy
Initializing the hsa runtime succeeded.
Checking finalizer 1.0 extension support succeeded.
Generating function table for finalizer succeeded.
Getting a gpu agent succeeded.
Querying the agent name succeeded.
The agent name is gfx701.
Querying the agent maximum queue size failed.

**Comment by Dekken** [comment]
also with sax no gdb

rocm/runtime/src/core/runtime/default_signal.cpp:91: virtual hsa_signal_value_t core::DefaultSignal::WaitRelaxed(hsa_signal_condition_t, hsa_signal_value_t, uint64_t, hsa_wait_state_t): Assertion `!g_use_interrupt_wait && "Use of non-host signal in host signal wait API."' failed.

**Comment by Dekken** [comment]
Could this message be important

drm:ci_dpm_sw_init [amdgpu]] *ERROR* Invalid PCC GPIO: 13!

**Comment by Dekken** [comment]
Any thoughts?

**Comment by jedwards-AMD** [comment]
Can you upgrade to the 1.3.1 build and try and reproduce the error?

**Comment by Dekken** [comment]
certainly, will try get it tonight, can you tell me when that was pushed, and if it is also the default branches, I rebuilt everything over the weekend so I could have done it already without realising and that's why I've stopped getting segfaults, will confirm tonight,

Thanks

**Comment by Dekken** [comment]
instant segfault on both vector_copy and saxpy

**Comment by Dekken** [comment]
rebuilt with debug symbols, and now back to queue size failed with or without debug, very odd

**Comment by Dekken** [comment]
The only difference I can consider is that I rebooted and it stopped segfaulting, I'll reboot a few times and diff the dmesg outputs to see if there's something there.

**Comment by Dekken** [comment]
Could it be possible that having two GPUs might be a problem?

**Comment by Dekken** [comment]
[dmesg | grep amd](https://gist.githubusercontent.com/Dekken/5551dddf66a7321bc3fc65b89f77c4ee/raw/6f21e23d4555cf4fd28188ecd5754da72df55e1e/gistfile1.txt)

**Comment by Dekken** [comment]
I've installed the repo kernel, and had tried again with zero difference, I will try again now that there as been some commits.

**Comment by jedwards-AMD** [comment]
Please send me the following output:
.
sudo lspci -xxxx &> pciedumphex.txt
sudo lspci -vvvv &> pciedump.txt
sudo lspci -t &> pcietopo.txt
sudo dmidecode > dmidecode.txt
.

**Comment by Dekken** [comment]
[sudo lspci -xxxx &> pciedumphex.txt](https://raw.githubusercontent.com/Dekken/gist/master/pciedumphex.txt)
[sudo lspci -vvvv &> pciedump.txt](https://raw.githubusercontent.com/Dekken/gist/master/pciedump.txt)
[sudo lspci -t &> pcietopo.txt](https://raw.githubusercontent.com/Dekken/gist/master/pcietopo.txt)
[sudo dmidecode > dmidecode.txt](https://raw.githubusercontent.com/Dekken/gist/master/dmidecode.txt)

**Comment by Dekken** [comment]
This has been resolved since some recent commits, not sure how.

**Comment by jedwards-AMD** [comment]
I looked at your output and you are running with two Hawaii 290's. These should be supported, but do not allow atomic support in kernels. The vector_copy sample doesn't use atomics, and should not have caused an issue. Did you reboot your system between runs?

**Comment by Dekken** [comment]
I'm actually running two XFX 390 BEs, but they appear as 290, yeah I
noticed previously that it would segfault,  then I'd reboot and it would
error but not segfault. All seems OK now though, could you provide more
info (link) on atomics you mentioned  please?

On 6 Dec 2016 10:24 p.m., "James Edwards" <notifications@github.com> wrote:

I looked at your output and you are running with two Hawaii 290's. These
should be supported, but do not allow atomic support in kernels. The
vector_copy sample doesn't use atomics, and should not have caused an
issue. Did you reboot your system between runs?

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/RadeonOpenCompute/ROCR-Runtime/issues/17#issuecomment-265292430>,
or mute the thread

**Comment by gstoner** [comment]
Here is an article
https://github.com/RadeonOpenCompute/RadeonOpenCompute.github.io/blob/master/ROCmPCIeFeatures.md

On Dec 6, 2016, at 11:28 AM, James Edwards <notifications@github.com<mailto:notifications@github.com>> wrote:


Please send me the following output:
.
sudo lspci -xxxx &> pciedumphex.txt
sudo lspci -vvvv &> pciedump.txt
sudo lspci -t &> pcietopo.txt
sudo dmidecode > dmidecode.txt
.

**Comment by Dekken** [comment]
Thanks for that, any chance you can provide a list of what cards support atomics, and what don't. Is there a suggested work around for unsupported cards? Like CPU delegation?

**Comment by gstoner** [comment]
All GFX8 and newer cards.

greg
On Dec 7, 2016, at 10:42 AM, ♦♣♠♥ <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks for that, any chance you can provide a list of what cards support atomics, and what don't. Is there a suggested work around for unsupported cards? Like CPU delegation?
