### ISSUE TITLE
Install dependency problem

### ISSUE THREAD

**Issue by zgu153522** [RadeonOpenCompute/ROCR-Runtime#2]
The newest update to ROCR that uses 2 packages instead of 1 causes an install problem for me: 
`hsa-rocr-dev depends on hsakmt-roct-dev (= 2.0.0); however:
  Package hsakmt-roct-dev is not installed.`

I do have the latest ROCK (1.0 release) installed, which should have included ROCT.

**Comment by jedwards-AMD** [comment]
We are moving to a repository based distribution system today, and this package dependency should be resolved. The packages here will be removed. Sorry for the confusion. I will update this comment when we go live.

**Comment by zgu153522** [comment]
Issue resolved in new release
