### ISSUE TITLE
ROCM 1.6 Assertion failure on Bristol Ridge APU: ROCR-Runtime/src/core/runtime/runtime.cpp:162: void core::Runtime::RegisterAgent(core::Agent*): Assertion `system_regions_fine_.size() > 0' failed.

### ISSUE THREAD

**Issue by tstellar** [RadeonOpenCompute/ROCR-Runtime#27]
The full stack trace is below.  It looks like the root cause is that the kernel reports mem_banks_count as 0:

user@host ]$ cat /sys/devices/virtual/kfd/kfd/topology/nodes/0/properties 
cpu_cores_count 4
simd_count 40
mem_banks_count 0
caches_count 8
io_links_count 0
cpu_core_id_base 16
simd_id_base 2147483648
max_waves_per_simd 40
lds_size_in_kb 64
gds_size_in_kb 0
wave_front_size 64
array_count 1
simd_arrays_per_engine 0
cu_per_simd_array 10
simd_per_cu 4
max_slots_scratch_cu 32
vendor_id 0
device_id 0
location_id 0
max_engine_clk_ccompute 3100

src/core/runtime/runtime.cpp:162: void core::Runtime::RegisterAgent(core::Agent*): Assertion `system_regions_fine_.size() > 0' failed.

#4  0x00007ffff7b24782 in core::Runtime::RegisterAgent (this=0x6179b0, agent=0x61d720)
    at src/core/runtime/runtime.cpp:162
#5  0x00007ffff7b0e43b in amd::DiscoverCpu (node_id=0, node_prop=...) at src/core/runtime/amd_topology.cpp:68
#6  0x00007ffff7b0e83d in amd::BuildTopology () at src/core/runtime/amd_topology.cpp:175
#7  0x00007ffff7b0e8cb in amd::Load () at src/core/runtime/amd_topology.cpp:191
#8  0x00007ffff7b27909 in core::Runtime::Load (this=0x6179b0) at src/core/runtime/runtime.cpp:992
#9  0x00007ffff7b24381 in core::Runtime::Acquire () at src/core/runtime/runtime.cpp:113
#10 0x00007ffff7b11a8b in HSA::hsa_init () at src/core/runtime/hsa.cpp:194
#11 0x00007ffff7b39537 in hsa_init () at src/core/common/hsa_table_interface.cpp:61

**Comment by tstellar** [comment]
After more investigation, it looks like the problem is that when the amdgpu module loads on boot, it is not correctly initializing the amdkfd module.  However, If I blacklist the amdgpu module and then manually modprobe it after the system boots, then this assert goes away and the device is detected correctly.  This is on Fedora 26.

**Comment by fxkamd** [comment]
Is amdkfd in your initial ramdisk? If not, does it help if you add it?

**Comment by tstellar** [comment]
I was seeing this with the problem with the rocm-1.6 kernel, but not with upstream 4.14-rc4.  When I get a chance I'll go back and check if amdkfd is in the ramdisk.

**Comment by jlgreathouse** [comment]
Are you still seeing this problem on more recent ROCm installations? I have a Bristol Ridge APU at my desk and was unable to recreate this on either ROCm 1.9.1 or ROCm 1.9.2.
