### ISSUE TITLE
libsp3.a for FreeBSD

### ISSUE THREAD

**Issue by iotamudelta** [RadeonOpenCompute/ROCR-Runtime#3]
I am in the process of porting rocr to FreeBSD. Everything compiles already in thunk and runtime (I will send patches after cleanup and testing), however linking the runtime fails due to the missing libsp3.a. Is there a chance to obtain either the library or, under NDA, the sources for compiling it myself for our ports tree?

Thanks so much for this project and your time!

**Comment by gstoner** [comment]
I am going to talk to the team about this .  I get back to you hopefully by end of day monday.

greg
On Apr 23, 2016, at 9:35 PM, iotamudelta <notifications@github.com<mailto:notifications@github.com>> wrote:


I am in the process of porting rocr to FreeBSD. Everything compiles already in thunk and runtime (I will send patches after cleanup and testing), however linking the runtime fails due to the missing libsp3.a. Is there a chance to obtain either the library or, under NDA, the sources for compiling it myself for our ports tree?

Thanks so much for this project and your time!

**Comment by jedwards-AMD** [comment]
We have provided a pre-compiled version of libsp3.a in the src/utils directory, along with header files. What is the compilation error that you are getting?

**Comment by jedwards-AMD** [comment]
We are currently in discussions with are legal team to open source this library.

**Comment by iotamudelta** [comment]
Thanks for your response. But this precompiled liubrary is for Linux w/ GCC toolchain, not FreeBSD w/ llvm toolchain.

I get a dwarf error:

/usr/bin/ld: Dwarf Error: found dwarf version '3', this reader only handles version 2 information.

(which one may be able to fix but it is not recommended since our GCC base compiler is stuck at 4.2 and hence DWARF2).

I also get a bunch of missing references after that. Examples below:

/usr/ports/devel/rocr-runtime/work/ROCR-Runtime-6d22b88/src/core/../utils/sp3/libsp3.a(sp3-lex.o): In function `yy_fatal_error.isra.0':
sp3-lex.c:(.text+0x7): undefined reference to `stderr'
/usr/ports/devel/rocr-runtime/work/ROCR-Runtime-6d22b88/src/core/../utils/sp3/libsp3.a(sp3-lex.o): In function `yylex_init_extra':
sp3-lex.c:(.text+0x361): undefined reference to `__errno_location'
sp3-lex.c:(.text+0x381): undefined reference to `__errno_location'
/usr/ports/devel/rocr-runtime/work/ROCR-Runtime-6d22b88/src/core/../utils/sp3/libsp3.a(sp3-lex.o): In function `yylex_init':
sp3-lex.c:(.text+0x4e1): undefined reference to `__errno_location'
sp3-lex.c:(.text+0x4f9): undefined reference to `__errno_location'
/usr/ports/devel/rocr-runtime/work/ROCR-Runtime-6d22b88/src/core/../utils/sp3/libsp3.a(sp3-lex.o): In function `yy_create_buffer':
sp3-lex.c:(.text+0x5b3): undefined reference to `__errno_location'
/usr/ports/devel/rocr-runtime/work/ROCR-Runtime-6d22b88/src/core/../utils/sp3/libsp3.a(sp3-lex.o):sp3-lex.c:(.text+0xd36): more undefined references to `__errno_location' follow
/usr/ports/devel/rocr-runtime/work/ROCR-Runtime-6d22b88/src/core/../utils/sp3/libsp3.a(sp3-lex.o): In function `yylex':
sp3-lex.c:(.text+0x1363): undefined reference to `stdin'
sp3-lex.c:(.text+0x1376): undefined reference to `stdout'
sp3-lex.c:(.text+0x1941): undefined reference to `__strdup'

which I put on the wrong OS+toolchain+DWARF combination of the precompiled libsp3.a.

Open-source would be for us preferred. The fact that we can and are porting amdgpu/amdkfd/rocr/... to FreeBSD right now is due to them being open-source and permissively licensed. Thank you!

**Comment by iotamudelta** [comment]
Hi, just checking what the status on the legal review is :-)

If open-sourcing is too far away, I'd be happy to compile under NDA for FreeBSD.

**Comment by mattmacy** [comment]
@gstoner does that mean it's been open sourced or it's not going to be open sourced?
