### ISSUE TITLE
Page not present or supervisor privilege

### ISSUE THREAD

**Issue by VincentSC** [RadeonOpenCompute/ROCR-Runtime#52]
Since ROCm 2.0 we get about the same as #50, but then in [rocPRIM](https://github.com/ROCmSoftwarePlatform/rocPRIM) and only on older GPUs (specifically S9300, Fiji architecture). Ubuntu 16.04.5, kernel 4.13. It works perfectly on a newer GPU.

> Memory access fault by GPU node-2 (Agent handle: 0x1edfe60) on address 0x1a0490d000. Reason: Page not present or supervisor privilege. Aborted (core dumped)

Thing is that it happens irregularly, which makes it difficult to debug. As it worked before and still works on newer GPUs, we thought it was a good idea to ask for help to pinpoint the problem. The reason to submit the issue here in ROCr-runtime is because it looks like a runtime-error. It could also be a problem with the compiler or with rocPRIM, but understanding why it's not ROCr would help in understanding the problem.

To replicate:
- run rocPRIM's tests on a Fiji GPU several times

**Comment by jlgreathouse** [comment]
I strongly suspect that this is a compiler problem, as this is a page fault caused by the kernel. Is there any chance you could try rolling back your versions of HCC (and HIP?) to 1.9.2 and see if the problem persists?

**Comment by whchung** [comment]
+ @sunway513 @parallelo . We are seeing similar issues reported by users on TensorFlow with `gfx803`. The issue is not visible on `gfx900`.

**Comment by VincentSC** [comment]
Let's try on 2.1 and if that doesn't work we'll roll back to 1.9.2 - this to prevent further delay of our project.

Is ROCm 2.1 safe to upgrade from 2.0, or should I fully remove 2.0 first?

**Comment by skeelyamd** [comment]
It looks like the compiler issue has now been fixed.

**Comment by ex-rzr** [comment]
What version of the compiler will include this fix?

I'm asking because HCC 1.3.19212-ef84ec5-7c03a2e-04d2753 from http://repo.radeon.com/rocm/apt/.apt_2.5 does not include it.

**Comment by skeelyamd** [comment]
I'll ask HCC if they can comment on that.  From hcc#1024 it appears that the fix is in LLVM and HCC should pick it up the next time they pull.
