### ISSUE TITLE
Compilation terminated with "fatal error: hsakmt.h: No such file or directory"

### ISSUE THREAD

**Issue by aurotripathy** [RadeonOpenCompute/ROCR-Runtime#54]
I'm unable to build ROCR-Runtime from source. I've also looked at #47
My build steps are:

Download per instructions here:
`https://github.com/RadeonOpenCompute/ROCm#downloading-the-rocm-source-code`
 
Then
```
cd  ~/ROCm/ROCR-Runtime/src
mkdir build
cd build
cmake ..
make
```
Error follows:
```
-rw-rw-r--  1 prj47-rack-76 prj47-rack-76 45307 Feb 28 19:34 Makefile
prj47-rack-76@prj47-rack-76:~/ROCm/ROCR-Runtime/src/build$ make
Scanning dependencies of target hsa-link
[  0%] Built target hsa-link
Scanning dependencies of target hsa-runtime64
[  2%] Building CXX object CMakeFiles/hsa-runtime64.dir/core/util/lnx/os_linux.cpp.o
[  5%] Building CXX object CMakeFiles/hsa-runtime64.dir/core/util/small_heap.cpp.o
[  8%] Building CXX object CMakeFiles/hsa-runtime64.dir/core/util/timer.cpp.o
[ 11%] Building CXX object CMakeFiles/hsa-runtime64.dir/core/runtime/amd_blit_kernel.cpp.o
In file included from /home/prj47-rack-76/ROCm/ROCR-Runtime/src/core/inc/agent.h:54:0,
                 from /home/prj47-rack-76/ROCm/ROCR-Runtime/src/core/inc/blit.h:48,
                 from /home/prj47-rack-76/ROCm/ROCR-Runtime/src/core/inc/amd_blit_kernel.h:50,
                 from /home/prj47-rack-76/ROCm/ROCR-Runtime/src/core/runtime/amd_blit_kernel.cpp:43:
/home/prj47-rack-76/ROCm/ROCR-Runtime/src/core/inc/queue.h:57:20: fatal error: hsakmt.h: No such file or directory
compilation terminated.
CMakeFiles/hsa-runtime64.dir/build.make:134: recipe for target 'CMakeFiles/hsa-runtime64.dir/core/runtime/amd_blit_kernel.cpp.o' failed
make[2]: *** [CMakeFiles/hsa-runtime64.dir/core/runtime/amd_blit_kernel.cpp.o] Error 1
CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/hsa-runtime64.dir/all' failed
make[1]: *** [CMakeFiles/hsa-runtime64.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2
prj47-rack-76@prj47-rack-76:~/ROCm/ROCR-Runtime/src/build$

```

**Comment by skeelyamd** [comment]
It looks like you are missing the path to the thunk (roct) headers.  If you run ccmake or cmake-gui you should see an entry, likely blank, for the thunk path.  The thunk library is usually installed to /opt/rocm/lib/libhsakmt.so and the header to /opt/rocm/include/.  If you are using local builds for the thunk then please point to where ever you have your local header and library.

**Comment by aurotripathy** [comment]
Thanks, @skeelyamd 
ccmake provides the following and I filled out HSAKMT_INC_PATH. 
```
CMAKE_BUILD_TYPE
CMAKE_INSTALL_PREFIX             /usr/local
HSAKMT_INC_PATH                  /opt/rocm/include
HSAKMT_LIB_PATH                  /opt/rocm/lib
```

That got past the missing `hsakmt.h` header but gave new erors.

```
In file included from /home/prj47-rack-76/ROCm/ROCR-Runtime/src/core/inc/agent.h:53:0,
                 from /home/prj47-rack-76/ROCm/ROCR-Runtime/src/core/inc/blit.h:48,
                 from /home/prj47-rack-76/ROCm/ROCR-Runtime/src/core/inc/amd_blit_kernel.h:50,
                 from /home/prj47-rack-76/ROCm/ROCR-Runtime/src/core/runtime/amd_blit_kernel.cpp:43:
/home/prj47-rack-76/ROCm/ROCR-Runtime/src/core/inc/isa.h:63:10: error: ‘hsa_wavefront_t’ does not name a type
   static hsa_wavefront_t Handle(const Wavefront *object) {
          ^
/home/prj47-rack-76/ROCm/ROCR-Runtime/src/core/inc/isa.h:68:34: error: ‘hsa_wavefront_t’ does not name a type
   static Wavefront *Object(const hsa_wavefront_t &handle) {
                                  ^
/home/prj47-rack-76/ROCm/ROCR-Runtime/src/core/inc/isa.h:74:22: error: ‘hsa_wavefront_info_t’ does not name a type
   bool GetInfo(const hsa_wavefront_info_t &attribute, void *value) const;
                      ^
/home/prj47-rack-76/ROCm/ROCR-Runtime/src/core/inc/isa.h: In static member function ‘static core::Wavefront* core::Wavefront::Object(const int&)’:
/home/prj47-rack-76/ROCm/ROCR-Runtime/src/core/inc/isa.h:69:70: error: request for member ‘handle’ in ‘handle’, which is of non-class type ‘const int’
     Wavefront *object = amd::hsa::common::ObjectAt<Wavefront>(handle.handle);

```

**Comment by aurotripathy** [comment]
Thanks @skeelyamd 
I had to point it to a local copy:
`cmake .. -DCMAKE_LIBRARY_PATH=/opt/rocm/lib/ -DCMAKE_INCLUDE_PATH=/home/prj47-rack-76/ROCm/ROCT-Thunk-Interface/include
`

**Comment by skeelyamd** [comment]
That indicates something is wrong with the roct header installation.  I'll forward this to the roct team and see if we can reproduce it.

**Comment by saitam757** [comment]
@skeelyamd Hi. I'm trying to package the ROCR for Solus Linux and it's ... how could I say ... quite challenging. I run into the same problem as @aurotripathy . I could compile the ROC-Thunk-Interface libraries. In order to adopt to the non-standard installation locations I compare them with those in the official ROCm docker container. Thus, I created `/opt/rocm/lib` and `/opt/rocm/include` and copied the libs and header files. Additionally I created `/opt/rocm/libhsakmt/` containing a libhsakmt.pc_  containing information for include and library paths. Then, I run cmake with different configurations
-   `cmake .. -DCMAKE_LIBRARY_PATH=/opt/rocm/lib/ -DCMAKE_INCLUDE_PATH=/opt/rocm/include` as @aurotripathy suggested
- `cmake -D CMAKE_PREFIX_PATH=/opt/rocm/libhsakmt ..` as in the official documentation
Both ways result in 
`/home/xxxxx/native_repo/RocR/ROCR-Runtime-roc-2.4.0/src/core/inc/queue.h:57:10: fatal error: hsakmt.h: No such file or directory
Does anybody has a clue what I'm doing wrong? Thanks.
 #include "hsakmt.h"
`

**Comment by skeelyamd** [comment]
The readme is sadly out of date.  With a fresh cmake cache and no cmake arguments ROCr searches some default paths for libhsakmt headers and library and attempts to set its paths based on the search but as you have seen that can readily fail.  Ultimately you can point cmake anywhere you like for this.

After initial configuration cmake cache will hold 2 variables, HSAKMT_INC_PATH and HSAKMT_LIB_PATH, set according to the path search (so may be blank if the search fails).  HSAKMT_INC_PATH needs to be pointed at the directory which holds the libhsakmt headers (hsakmt.h, hsakmttypes.h, linux/...).  HSAKMT_LIB_PATH should point to the directory which holds libhsakmt.so.

You can set those with any standard cmake cache tool (ccmake or cmake-gui for instance).  Or you can set them on the command line with -DHSA_INC_PATH:STRING=...   You can also leave out the type specifier and just write -DHSA_INC_PATH=... but if you do then standard cmake cache tools may not handle the variable properly and can leave it out of the interface.  That just makes it harder to modify manually if you ever need to.

**Comment by saitam757** [comment]
It worked, thank you. Now I proceed with the next library of the ROCm stack. Maybe you should update the documentation on this. I would be easier for people to transfer ROCm into distribution packages.

**Comment by skeelyamd** [comment]
The readme will be updated in 2.5.  Thanks for pointing this out!
