### ISSUE TITLE
Software built on ROCm 2.2 fails to run on ROCm 2.3

### ISSUE THREAD

**Issue by VincentSC** [RadeonOpenCompute/ROCR-Runtime#60]
All failing tests give `symbol lookup error: undefined symbol: _ZN8hip_impl14function_namesB5cxx11Eb`. It seems that something was removed, which makes 2.2 and 2.3 not binary compatible.

**Comment by skeelyamd** [comment]
Hi.  That symbol is a HIP function, not a ROCr API.  You can find the HIP repo here: https://github.com/ROCm-Developer-Tools/HIP

**Comment by skeelyamd** [comment]
I copied the bug report to https://github.com/ROCm-Developer-Tools/HIP/issues/1026.  I don't see how to add you as a watcher so I just tagged you.
