### ISSUE TITLE
How to set LOADER_OPTIONS_APPEND?

### ISSUE THREAD

**Issue by zjunweihit** [RadeonOpenCompute/ROCR-Runtime#62]
Try to set dump-all and dump-dir, but they are not working as "unknown option".
What's the format to set it?

Thanks.

**Comment by skeelyamd** [comment]
LOADER_OPTIONS_APPEND=-dump-all <executable and options>

It seems to be working.  Since compilation is not JIT the disassembly will be raw.  https://rocm-documentation.readthedocs.io/en/latest/ROCm_Tools/ROCm-Tools.html has instructions for using the disassembler.

You may want to try /opt/rocm/bin/extractkernel instead.  This will let you extract kernels without having to run the program.

**Comment by zjunweihit** [comment]
@skeelyamd thanks for your reply.

yes, you're right, we need "-" before each parameter. (also found it by gdb...)
it works in my case below:
```
LOADER_OPTIONS_APPEND=”-dump-all=1 -dump-dir=/home/zjunwei/”
```

and I tried extractkernel with co and app binary, but no .kernel section found.
```
/opt/rocm/bin/extractkernel -i vector_add.co 
No .kernel section found

/opt/rocm/bin/extractkernel -i vector_add
No .kernel section found
```

BTW, is it possible to extract kernel args and their data type at the same time? or it's only available by comgr API?

**Comment by skeelyamd** [comment]
Code objects built with version v3 require comgr to interpret.

**Comment by zjunweihit** [comment]
@skeelyamd thanks for your comments.

version v3 means the language versin in hsaco?
```
LanguageVersion: [ 2, 0 ]
```

/opt/rocm/bin/extractkernel works with hcc built binary.
* dump hsaco and isa file

Can we get kernel info like comgr in hsa runtime?

**Comment by skeelyamd** [comment]
In v3 metadata has been moved and is no longer part of what is given to the ROCr loader.  Accessing the metadata would require new APIs to give ROCr access the full ELF object.  The intention is that the language layer would be consuming the metadata to bind with user provided arguments and language built-ins.  I'll pass on the ask but as it stands today ROCr doesn't ever see the ELF section that contains the metadata.

Relevant info from LLVM:
https://llvm.org/docs/AMDGPUUsage.html#amdgpu-amdhsa-code-object-metadata-v3

**Comment by zjunweihit** [comment]
@skeelyamd thanks much.
it's enough for me now :)
Going to close this issue.
