### ISSUE TITLE
HSA_EXT_AGENT_INFO_IMAGE_*D_MAX_ELEMENTS returns HSA_STATUS_ERROR_NOT_INITIALIZED

### ISSUE THREAD

**Issue by jrprice** [RadeonOpenCompute/ROCR-Runtime#7]
Calling the `hsa_agent_get_info` function with any of the `HSA_EXT_AGENT_INFO_IMAGE_*D_MAX_ELEMENTS` queries is returning `HSA_STATUS_ERROR_NOT_INITIALIZED`. All other queries are working fine and I can run full HSA programs on the device.

I'm using ROCm 1.1.0 on Ubuntu 14.04 with a Kaveri APU (A10-7850K).

**Comment by jedwards-AMD** [comment]
The image extension is not supported in the ROCm stack yet. You will notice that there is no libhsa-ext-image64.so.x library
