### ISSUE TITLE
Support for no exceptions

### ISSUE THREAD

**Issue by chsigg** [RadeonOpenCompute/ROCR-Runtime#70]
Google would like to build the ROCR-Runtime internally, but we do not use C++ exceptions. Would it be possible to support this case through some `#if __cpp_exceptions` macros?

**Comment by skeelyamd** [comment]
Removing exceptions is not something we currently have a plan to do.  ROCr uses exceptions for terminal error reporting.  When we encounter a condition that needs the API to return an error code we throw a custom exception type, catch it at the C interface and return the error code.  Many of the places this is used are in object constructors where we can't return an error code.

From the PR conversation it seems you may be commenting out the throws.  Doing this will result in errors not being caught and potentially leading to segfault or, possibly worse, subtle data corruption.

Can I ask what the context is for the request?  If it helps we, don't leak exceptions out of the library or expect client code to support them.  They are strictly an internal implementation detail.

**Comment by chsigg** [comment]
Google doesn't use C++ exceptions in their own code, but apparently it's Ok for libraries to use exceptions internally. Sorry, I should have checked internally first. I can compile this repo as-is without having to silence exceptions. Closing.
