### ISSUE TITLE
How to test ROCR-Runtime?

### ISSUE THREAD

**Issue by s-bernard** [RadeonOpenCompute/ROCR-Runtime#93]
Hi, I’m trying to install ROCm stack on Arch Linux (I know, it’s not officially supported) but I cannot manage to get a version of HIP that pass its tests. On the same machine, if I compile HIP in an ubuntu docker, it works as expected.

Thus, I want to check all components.
How do I test that my compiled ROCR-Runtime on Arch Linux is OK?

**Comment by kentrussell** [comment]
An easy method is to run https://github.com/RadeonOpenCompute/rocminfo or https://github.com/RadeonOpenCompute/rocm_bandwidth_test . They are pretty standard sanity checks for ROCr.

**Comment by s-bernard** [comment]
Both are working, so I’ll look somewhere else.
Thanks for your answer.

**Comment by powderluv** [comment]
Im looking for some basic unit tests for rocr-runtime too. Did you find any ?  Some basic unit tests would be great. looking at rocm_bandwidth_test now.
